---
container_policy_disable_docker_system_service: true
container_policy_enforce_root_docker_cli_block: true
container_policy_enforce_podman_service_account_only: true
container_policy_block_script_path: /etc/profile.d/disable-root-docker-and-podman.sh
